---
title: "counting-comparisons.Rmd"
author: "Steve Lianoglou"
date: "May 26, 2016"
output:
  html_document:
    self_contained: false
    toc: true
    toc_depth: 3
    toc_float: true
    lib_dir: libs
---

```{r setup, include=FALSE}
library(FacileAtezo)
library(ggplot2)
library(plotly)
theme_set(theme_bw())
knitr::opts_chunk$set(
  echo=TRUE, warning=FALSE, message=FALSE, error=FALSE, dpi=150)
```

# Overview

We want to compare different counting modes from `summarizeOverlaps`. Here we
compare:

  * `mode='Union'`
  * `mode='IntersectionStrict'`

We are using the FacileAtezo package to access these data via their respective
databases.

```{r data-setup}
dbu <- AtezoDb('~/workspace/data/facile/atezo/v01/AtezoDb-countingUnion.sqlite')
dbi <- AtezoDb('~/workspace/data/facile/atezo/v01/AtezoDb-countingIntersectionStrict.sqlite')
```

# Comparison of ARG1 expression

Let's fetch ARG1 (entrez: 383) expression from both modes

```{r load-arg1}
arg1.u <- fetch_expression(dbu, feature_ids='383') %>%
  cpm(log=TRUE, prior.count=5) %>%
  rename(count.u=count, cpm.u=cpm)
arg1.i <- fetch_expression(dbi, feature_ids='383') %>%
  cpm(log=TRUE, prior.count=5) %>%
  rename(count.i=count, cpm.i=cpm)
dat <- inner_join(arg1.u, arg1.i) %>%
  mutate(barcode=paste(dataset, sample_id, sep='_'))
```

And plot via plotly for interactivity

```{r arg1-plotly, fig.width=3, fig.height=3}
gg <- ggplot(dat, aes(cpm.u, cpm.i)) +
  geom_point(aes(text=barcode, color=dataset)) +
  xlab("Union") +
  ylab("IntersectionStrict") +
  geom_abline(intercept=0, slope=1, color='red') +
  ggtitle("Unioin vs IntersectionStrict (ARG1)")
ggplotly(gg)
```
