datasets:
  default: testFacileDataSet
  groups:
    "Example Data Sets":
      - exampleFacileDataSet
      - testFacileDataSet
genesets:
  default:
    - Hallmark
    - KEGG
    - Reactome
    - ISR
    - ISR groom
