on:
  push:
    branches:
      - main
    paths:
      - 'R/**'
      - 'DESCRIPTION'
      - 'NAMESPACE'
      - 'src/**'
      - 'tests/**'
  pull_request:
  schedule:
    # Rerun checks daily, after facilebio/facilebio_base_extra is rebuilt.
    # This will catch failures due to changes in functionality of packages
    # we depend on.
    # facilebio_base_extra builds every day 4AM pacific time (11 AM UTC), so
    # we will build this an hour after that (the same time facilebio/facilebio)
    - cron: '0 12 * * *'
  workflow_dispatch:
    inputs:
      dummy:
        description: 'A dummy variable to enable manual workflow execution'
        required: false
        default: 'gitty up'

name: R-CMD-check

env:
  has_testthat: 'true'

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     image: ['facilebio/facilebio', 'facilebio/facilebio:devel']
    # container: ${{ matrix.image }}
    container: facilebio/facilebio
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup R
        uses: r-lib/actions/setup-r@v1
        with:
          install-r: false

      - name: Install dependencies
        run: remotes::install_deps(dependencies = TRUE, upgrade = FALSE)
        shell: Rscript {0}

      - name: Run BiocCheck
        env:
          DISPLAY: 99.0
        run: |
          BiocCheck::BiocCheck(
              dir('check', 'tar.gz$', full.names = TRUE),
              `quit-with-status` = TRUE,
              `no-check-R-ver` = TRUE,
              `no-check-bioc-help` = TRUE,
              `no-check-coding-practices` = TRUE)
        shell: Rscript {0}
