on:
  schedule:
    # Only push the test coverage up on a schedule. We can use the full
    # facilebio image for this for expediency
    - cron: '30 12 * * *'
  workflow_dispatch:
    inputs:
      dummy:
        description: 'A dummy variable to enable manual workflow execution'
        required: false
        default: 'gitty up'

name: test-coverage

jobs:
  test-coverage:
    runs-on: ubuntu-latest
    container: facilebio/facilebio
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      NOT_CRAN: true
      CI: true

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup R
        uses: r-lib/actions/setup-r@v1
        with:
          install-r: false

      - name: Test coverage
        run: covr::codecov(quiet = FALSE)
        shell: Rscript {0}
